### ISSUE TITLE
If column header is set empty string (like Header: "") then it throws error if id property is not passed.

### ISSUE THREAD

**Issue by sagarCS** [TanStack/react-table#3794]
const Colums = [
      {
      Header: "",
      accessor: (data: any) => {
        if (!data.title) {
          return <span className="mutedTitle">Untitled</span>
        }
        return <span>{data.title}</span>
      },
      // id: 'title',
      default: true,
      addToColumnSelector: true,
      cssClass: 'titleCell'
    },
  ]
  
  I have passed the above column to the table, 
  if I set the header as an empty string and the id property is commented, then it throws an error as below
  
  Uncaught Error: A column ID (or string accessor) is required!
    at assignColumnAccessor (react-table.development.js:440:13)
    at eval (react-table.development.js:402:7)
    at Array.map (<anonymous>)
    at linkColumnStructure (react-table.development.js:397:20)
    at eval (react-table.development.js:1076:14)
    at updateMemo (react-dom.development.js:15463:19)
    at Object.useMemo (react-dom.development.js:15920:16)
    at Object.useMemo (react.development.js:1521:21)
    at useTable (react-table.development.js:1075:25)
    at InfiniteScrollTable (index.esm.js:24615:91)
    
   but if id is passed or Header is set as " " then it works ,
   so can someone please explain why this is happening?

**Comment by sagarCS** [comment]
Got it. Thanks @erpatterson11 for the explanation :+1:
